// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate environment variables
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error(
    '❌ Missing Supabase environment variables!\n' +
    'Please create a .env file in the root directory with:\n' +
    'VITE_SUPABASE_URL=your_supabase_url\n' +
    'VITE_SUPABASE_PUBLISHABLE_KEY=your_supabase_anon_key\n\n' +
    'You can find these values in your Supabase project settings under API.\n' +
    'Make sure you use the "anon public" key, NOT the "service_role" key.'
  );
} else {
  // Validate key format
  if (!SUPABASE_PUBLISHABLE_KEY.startsWith('eyJ')) {
    console.warn(
      '⚠️ Warning: Your API key doesn\'t look like a valid JWT token.\n' +
      'Make sure you\'re using the "anon public" key from Supabase Dashboard → Settings → API.\n' +
      'The key should start with "eyJ" (it\'s a JWT token).'
    );
  }
  
  // Validate URL format
  if (!SUPABASE_URL.includes('.supabase.co')) {
    console.warn(
      '⚠️ Warning: Your Supabase URL doesn\'t look correct.\n' +
      'It should be in the format: https://your-project-ref.supabase.co'
    );
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || 'https://placeholder.supabase.co',
  SUPABASE_PUBLISHABLE_KEY || 'placeholder-key',
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: false,
    },
    global: {
      headers: {
        'apikey': SUPABASE_PUBLISHABLE_KEY || 'placeholder-key',
      },
    },
  }
);